### ISSUE TITLE
Error starting Meteor app

### ISSUE THREAD

**Issue by Markusxmr** [TsumiNa/meteor-aurelia#2]
When I run the app I get the following error 

```
 While processing files with tsumina:meteor-aurelia (for target web.browser):
   packages/es/plugin/es-handler.js:13:1: file is not defined (at
   CompilerES.processFilesForTarget)
```

**Comment by TsumiNa** [comment]
@Markusxmr  Thank you for found that. since the server version have this issue. My local test shows all right.

before meteor package upload to server, they will be compiled locally, so there is hard to say what's wrong with this issue. I will check my local codes and upload it again. Please give me sometime to confirm these. 

Also you can clone this repo then use it as a local package. I think this should work :smile:

**Comment by TsumiNa** [comment]
@Markusxmr pushed a new release. please try it.

**Comment by Markusxmr** [comment]
Excelent! The app is running :+1: Great work.

**Comment by Markusxmr** [comment]
Btw just before the app runs, console logs the following 
```
Warning: Cannot read your 'tsconfig.json' file. Will use default compile options
Message: Typescript Compiler is running on: /home/marko/dev/meteor/au-ts
Error: [client/app/welcome.ts](1,28): Cannot find module 'aurelia-framework'.
Error: [collections/friends.ts](1,26): Cannot find name 'Mongo'.
Error: [collections/friends.ts](1,26): Cannot find name 'Mongo'.
```
What does it mean?

**Comment by TsumiNa** [comment]
@Markusxmr Do you think I should keep systemjs lonely? So you no need install meteor-typescript if you don't use typescript

**Comment by Markusxmr** [comment]
@TsumiNa Yeah, most of the time, it is a good practice to keep the separation, many users many use cases. 

Would it be good that system js get's included within this package? 
Or would it be possible for users to use system js and config.js for as easy as possible capability to add Aurelia packages so they don't have to go throug the hurdle of wrapping every Aurelia plugin for Atmosphere js (but there is maybe a the problem with bundling, since Aurelia is prebundled). 

If that is not possible, maybe when author does want to wrapp the plugin, to make it possible to hook it to system js and config js (again, the potential bundling issue).

Lots of ideas, just thinking out loud.

**Comment by Markusxmr** [comment]
I an not yet proficient enough to help you directly with writing advanced expressions, but if you have an idea how I can assist you, I'm here :)
