### ISSUE TITLE
Caching Compiler Error

### ISSUE THREAD

**Issue by Markusxmr** [TsumiNa/meteor-aurelia#3]
I started to port a advanced meteor todos app, and when using your package I get a caching compiler error. When using ahmedshuhel package, it runs ok.

Here is the link to the github repo of the app, so you could try to reproduce the issue
[aurelia-meteor-todos](https://github.com/Markusxmr/aurelia-meteor-todos)

**Comment by TsumiNa** [comment]
Got it! give me some times :+1:

**Comment by TsumiNa** [comment]
@Markusxmr Fixed it. Now compiler will output syntax errors. Some errors in your source files.

``` bash
=> Errors prevented startup:

   While processing files with tsumina:meteor-aurelia (for target web.browser):
   client/app/components/accounts/auth-join-page.au.js: Javascript syntax error: unknown:
   Unexpected token (1:40)
   client/app/components/accounts/auth-signin-page.au.js: Javascript syntax error: unknown:
   Unexpected token (1:40)
   client/app/components/left-panel.au.js: Javascript syntax error: unknown: Unexpected token
   (25:3)

   While processing files with tsumina:meteor-aurelia (for target web.browser):
   client/app/components/menu-open.html: HTML syntax error: Only certain elements like BR, HR,
   IMG, etc. (and foreign elements like SVG) are allowed to self-close
   </div>...="Show menu" />
   ^
```

For example: client/app/components/left-panel.au.js

``` js
import {inject, bindable, } from 'aurelia-framework';
import {Router} from 'aurelia-router';

@bindable('current_user')
@bindable('add_list')
@bindable('lists')
//@bindable('active_list_id')
@inject(Router)
export class LeftPanel {

  constructor(router){
    this.router = router;
  }

  addList() {
    Meteor.call("/lists/add", (err, res) => {
      if (err) {
        // Not going to be too fancy about error handling in this example app
        alert("Error creating list.");
        return;
      }
      // Go to the page for the new list
      this.router.navigateToRoute('lists', { list_id: res });
    });
  },

}
```

(1, 25) `,` is not allowed
(25, 3) `,` is not allowed

**Comment by Markusxmr** [comment]
Awesome! Fixed the original issue. Very helpfull. 
Unfortunately now when aurelia has started,  I get 

```
"Unhandled promise rejection Error: Error invoking App. Check the inner error for details.(…)".
(anonymous function)    @   aurelia.js:13851
```

Don't think it should be issue with an error in the source code.
Updated the repo
[aurelia-meteor-todos](https://github.com/Markusxmr/aurelia-meteor-todos)

**Comment by Markusxmr** [comment]
Most likely it is my error. Double checking....

Yep, forgot to add the necessary packages.

Again, awesome work :+1:

**Comment by Markusxmr** [comment]
Btw, when I do some cleanups in the code, feel free to add the todo app as an example in the readme if it is to your preference

**Comment by TsumiNa** [comment]
@Markusxmr Thank you! I will do that. Maybe you can make it as a live demo :smile:

**Comment by Markusxmr** [comment]
Will do that :smile:. Just to locate some minor issues to make it perfect

**Comment by Markusxmr** [comment]
I've put a live demo, it's not ideal, but it's working. Will add some missing features, when some time presents it self.
[Aurelia Meteor todos live demo](http://aurelia-todos.meteor.com/#/lists/ixR4M2itKNxWSbY4X)

**Comment by wasimf** [comment]
Hi, Where is the source code ? its not updated here https://github.com/Markusxmr/Aurelia-Meteor-Simple-Todo .

**Comment by TsumiNa** [comment]
@Markusxmr thanks, will add to readme next update!

**Comment by TsumiNa** [comment]
@wasimf https://github.com/Markusxmr/aurelia-meteor-todos this is you want

**Comment by wasimf** [comment]
👍
