### ISSUE TITLE
 Double caused .html templates in app

### ISSUE THREAD

**Issue by PGA68** [TsumiNa/meteor-aurelia#4]
=> Started proxy.
=> Started MongoDB.
Message: Using Systemjs Loader...
Message: Using Aurelia Framework...
=> Errors prevented startup:

   While determining active plugins:
   error: conflict: two packages included in the app (templating and tsumina:meteor-aurelia) are both trying to handle *.html

   While determining active plugins:
   error: conflict: two packages included in the app (templating and tsumina:meteor-aurelia) are both trying to handle *.html

=> Your application has errors. Waiting for file change.

**Comment by TsumiNa** [comment]
You must remove `blaze-html-templates` and `spacebars` packages.

This package will handle `*.html` files. Only the `index.html` under the root will be compiled to normal html template.

see change log for details in the readme
