### ISSUE TITLE
Custom Aurelia Plugins

### ISSUE THREAD

**Issue by uwascan** [TsumiNa/meteor-aurelia#5]
Hi, how do I install custom, third party aurelia plugins using this meteor integration package.

**Comment by TsumiNa** [comment]
@uwascan Yes, you can do that if you know how to create meteor package and know a little about systemjs API. You can see the [example](https://github.com/TsumiNa/meteor-ui-virtualization)here.

Alternatively, clone the plugin and use it directly.

#### Detail:

`meteor-aurelia` and `meteor-typescript` compile files with their package name as root path. If codes not in a package, package name is `null`, for example:
**main.sys.js**

``` js
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-animator-css')
    .plugin('tsumina:ui-virtualization');

  aurelia.start().then(a => a.setRoot('client/app'));
}
```

to **main.js**

``` js
System.register("client/main",[], function (_export) {
  'use strict';  
  _export('configure', configure);  
  function configure(aurelia) {  
    aurelia.use.standardConfiguration().developmentLogging().plugin('aurelia-animator-css').plugin('tsumina:ui-virtualization');
    aurelia.start().then(function (a) {
      return a.setRoot('client/app'); 
    }); 
  } 

  return { 
    setters: [], 
    execute: function () {} 
  }; 
}) 
```

Now assume the **main.sys.js** in a package named **yourname:package-name**. In this case, the package name will be used as the root path. 
 **main.js**

``` js
System.register("yourname:package-name/client/main",[], function (_export) {
  'use strict';  
  _export('configure', configure);  
  function configure(aurelia) {  
    aurelia.use.standardConfiguration().developmentLogging().plugin('aurelia-animator-css').plugin('tsumina:ui-virtualization');
    aurelia.start().then(function (a) {
      return a.setRoot('client/app'); 
    }); 
  } 

  return { 
    setters: [], 
    execute: function () {} 
  }; 
}) 
```

So if you create a aurelia package with a entry `index.sys.js` at your package root, Name your package **yourname:package-name**, and want other users load it like

``` js
plugin('yourname:package-name');
```

you should add a `lib/init.js` file to you package sources with content:

``` js
System.registerDynamic("yourname:package-name", ["yourname:package-name/index"], true, function($__require, exports, module) {
  ;
  var global = this,
      __define = global.define;
  global.define = undefined;
  module.exports = $__require('yourname:package-name');
  global.define = __define;
  return module.exports;
});
```

I'm trying to make these process simple for who don't know much about meteor package. Maybe Aurelia should officially create a repo to let others pr their plugins and port them to meteor style.
